#!/usr/bin/env python

import xattr
import sys

f = sys.argv[1]
x = xattr.xattr(f)

if len(sys.argv) == 4:
    k, v = sys.argv[2:]
    print "set %s to %s" % (k, v)
    x[k] = v
else:
    for k in x.keys():
        print k, x[k]
